### ISSUE TITLE
FileNotFoundError: Project root directory not found. Indicators: ['.project-root']

### ISSUE THREAD

**Issue by dxxxmmm** [winddori2002/MANNER#9]
Hello,autherHello Author, could you please tell me why there is an error here?
Here are track:
Traceback (most recent call last):
  File "/home/d/Pycode/manner/manner/train.py", line 11, in <module>
    pyrootutils.setup_root(__file__, indicator=".project-root", pythonpath=True)
  File "/home/d/anaconda3/envs/manner_env/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 151, in setup_root
    path = find_root(search_from, indicator)
  File "/home/d/anaconda3/envs/manner_env/lib/python3.9/site-packages/pyrootutils/pyrootutils.py", line 73, in find_root
    raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
FileNotFoundError: Project root directory not found. Indicators: ['.project-root']

**Comment by DL909** [comment]
I got this answer from another issue in other project. And for now it works well.
just create a empty file named '.project-root' in your working directory(I mean, the directory where your terminal stay.)
you can simply create it use touch:
touch .project-root
hope it works
